FROM deathhorn/onboard_env:deploy-v0.7

ARG HTTP_PROXY=""
ARG HTTPS_PROXY=""

WORKDIR /root/ws/

# timed-roslaunch
RUN apt update && \
    apt install -y ros-noetic-timed-roslaunch && \
    rm -rf /var/lib/apt/lists/*

# VINS-Fusion
RUN cd /root/ws/vins && \
    mkdir -p /root/ws/vins/src && \
    catkin config --extend /opt/ros/noetic && \
    cd /root/ws/vins/src && \
    git config --global http.proxy $HTTP_PROXY && \
    git config --global https.proxy $HTTPS_PROXY && \
    git clone https://github.com/flyingbitac/VINS-Fusion.git && \
    git config --global --unset http.proxy && \
    git config --global --unset https.proxy && \
    cd /root/ws/vins/ && \
    catkin build && \
    echo "source /root/ws/vins/devel/setup.bash" >> /root/.bashrc

WORKDIR /root/ws/

ENTRYPOINT ["bash", "-c", "service ssh restart && exec bash"]