FROM deathhorn/onboard_env:deploy-v0.3

ARG PROXY_HOST=""

# prebuild the glog and ceres solver for VINS-Fusion
RUN git config --global http.proxy $PROXY_HOST && \
    git config --global https.proxy $PROXY_HOST && \
    git clone https://github.com/flyingbitac/vins.git && \
    rm -rf /root/ws/vins/src/ && \
    git config --global --unset http.proxy && \
    git config --global --unset https.proxy

WORKDIR /root/ws/vins

RUN cd /root/ws/vins/glog/ && \
    chmod +x ./autogen.sh && chmod +x ./configure && \
    ./autogen.sh && ./configure && \
    make -j$(nproc) && make install && \
    apt-get update && \
    apt-get install liblapack-dev libsuitesparse-dev libgflags-dev libgoogle-glog-dev libgtest-dev -y && \
    cd /root/ws/vins/ceres-solver-2.0.0rc1/ && \
    mkdir build && cd build && \
    cmake .. && make -j$(nproc) && make install && \
    apt-get install ros-noetic-ddynamic-reconfigure && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root/ws/